info:
  component: 'Composite Service'

spring:
    application:
        name: composite
    zipkin:
        baseUrl: http://10.1.102.175:9411
    sleuth:
        enabled: true
        sampler:
            percentage: 1.0

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG

---
# For deployment without Docker containers
spring:
  profiles: default

server:
    port: 8083

hostnames:
  events: localhost:8082
  locations: localhost:8081
  tickets: localhost:8080

servicenames:
  events: events
  locations: locations
  tickets: tickets

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://localhost:8761}/eureka/

---
# For deployment in Docker containers
spring:
  profiles: docker

server:
    port: 80

hostnames:
  events: events
  locations: locations
  tickets: tickets

servicenames:
  events: eventservice
  locations: locationservice
  tickets: ticketservice

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
